import { sql } from '@vercel/postgres';
import type { Metadata } from "next";

import "./globals.css";
   

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // Достаем цвет из базы данных
  const { rows } = await sql`SELECT value FROM settings WHERE key = 'primary_color'`;
  const primaryColor = rows[0]?.value || '#000000'; // По умолчанию черный

  return (
    <html lang="ru">
      {/* Впрыскиваем CSS-переменную прямо в тег body */}
      <body style={{ '--primary': primaryColor } as React.CSSProperties}>
        {children}
      </body>
    </html>
  );
}